# =====================================================
# Data displayed on the Home (About Me) page.
#
# üí° Tip for Images / Logo:
# You can use either:
# 1. A full URL (e.g., https://example.com/logo.png)
# 2. A local file placed under /public/images/ and referenced with "/" (e.g., "/images/logo.png")
# =====================================================
# =====================================================
# üë§ Personal Information
# =====================================================

profile:
  name: "Cookie"
  headline: "Student"
  email: ""
  location: null
  profileImage: "/images/logo.png"

  links:
#    - name: "LinkedIn"
#      url: ""
#      icon:
#        name: "FaLinkedin"
#        package: "react-icons/fa6"

    - name: "Google Scholar"
      url: ""
      icon:
        name: "FaGoogleScholar"
        package: "react-icons/fa6"

    - name: "R√©sum√©"
      url: ""
      icon:
        name: "FaRegIdBadge"
        package: "react-icons/fa6"

    - name: "Github"
      url: "https://github.com/icevalon"
      icon:
        name: "FaGithub"
        package: "react-icons/fa6"

    - name: "Facebook"
      url: ""
      icon:
        name: "FaSquareFacebook"
        package: "react-icons/fa6"

  # you can use HTML syntax here (e.g. <br/>, <a>, <strong>, ...)
  biography: |
    Hi! I'm <strong>Cookie</strong>, a <em>high school student</em> passionate about <em>computers</em>. 
    I have strong interests in: 
     - Cybersecurity
     - Networking
     - Linux Internals & Computer architecture
    <div class="my-2"></div>
# # =====================================================
# # üéì Education Section
# # =====================================================

#education:
#  - degree: "Ph.D. in [Field]"
#    school: "[University Name]"
#    years: "20XX - Present"
#    logo: "https://upload.wikimedia.org/wikipedia/en/a/a1/Arizona_State_University_seal.svg"

#  - degree: "M.S. in Computer Science"
#    school: "National Taiwan University"
#    years: "2020 - 2022"
#    logo: "/images/ntu_logo.svg"

#  - degree: "B.S. in Computer Science"
#    school: "National Chengchi University"
#    years: "2018 - 2020"
#    logo: "/images/nccu_logo.svg"

# # =====================================================
# # üíº Work Experience Section
# # =====================================================

#workExperience:
#  - title: "[Job Title]"
#    company: "[Company Name]"
#    years: "20XX - Present"
#    logo: "/images/nvidia_logo.webp"

#  - title: "Software Engineering Intern"
#    company: "Google"
#    years: "Jul 2022 - Sep 2022"
#    logo: "/images/google_logo.svg"

 # - title: "Research Assistant"
 #   company: "University of Illinois Urbana-Champaign"
 #   years: "Jul 2019 - Sep 2019"
 #   logo: "/images/uiuc_logo.png"

# # =====================================================
# # üé§ Presentations / Talks Section
# # =====================================================

#talks:
#  - category: "Misc"
#    title: "[Your Talk Title Here]"
#    organization: "[Your Talk Location Here]"
#    date: "[Month Day, Year]"
#    link: "https://example.com/your-talk-link"
#    image: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Example_image.svg"

#  - category: "Workshop"
#    title: "Deep Learning with Keras"
#    organization: "University of Illinois Urbana-Champaign (UIUC)"
#    date: "Sep 4, 2019"
#    link: null
#    image: "https://pm25.github.io/images/uiuc-workshop.webp"

#  - category: "Workshop"
#    title: "Practical Guide to PyTorch"
#    organization: "ABC University"
#    date: "Dec 5, 2022"
#   link: "https://example.com/workshop-talk"
#    image: null

# # =====================================================
# # üõ°Ô∏è Professional Services
# # =====================================================

#services:
#  - category: "Misc"
#    role: "[Role]"
#    organization: "[Organization]"
#    date: "[Year]"
#    link: "https://example.com/workshop-talk"
#   image: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Example_image.svg"

  - category: "Research"
    role: "Reviewer"
    organization: "TPAMI 2024, NeurIPS 2025"
    date: "2024-2025"
    link: null
    image: null

  - category: "Research"
    role: "Program Committee Member"
    organization: "CVPR 2022"
    date: "2022"
    link: null
    image: null

 # - category: "Teaching"
 #   role: "Teaching Assistant"
 #   organization: "National Taiwan University - Data Structures & Algorithms"
 #   date: "2021"
 #   link: null
 #   image: null

# # =====================================================
# # üõ†Ô∏è Skills Section
# # =====================================================

skills:
  Programming:
    - name: "C"
      logo: "/images/c.svg"
      proficiency: "Experienced"
      description:

    - name: "Python"
      logo: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg"
      proficiency: Learning
      description: null

#    - name: "JavaScript"
#      logo: "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg"
#      proficiency: 
#      description: null

 # Web:
 #   - name: "React"
 #     logo: "https://upload.wikimedia.org/wikipedia/commons/3/30/React_Logo_SVG.svg"
 #     proficiency: Advanced
 #     description: null

 #  - name: "Typescript"
 #    logo: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Typescript.svg"
 #    proficiency: Fluent
 #    description: null

#    - name: "TailwindCSS"
#      logo: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Tailwind_CSS_Logo.svg"
#      proficiency: Fluent
#      description: null

#    - name: "Next.js"
#      logo: "https://logo.svgcdn.com/devicon/nextjs-original.png"
#      proficiency: Fluent
#      description: null

#  Machine Learning:
#    - name: "PyTorch"
#      logo: "https://upload.wikimedia.org/wikipedia/commons/1/10/PyTorch_logo_icon.svg"
#      proficiency: Experienced
#      description: null

#   - name: "TensorFlow"
#      logo: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg"
#      proficiency: Fluent
#      description: null

#    - name: "Keras"
#      logo: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Keras_logo.svg"
#      proficiency: Fluent
#      description: null

#  Research:
#    - name: "Machine Learning"
#      logo: "https://upload.wikimedia.org/wikipedia/commons/2/2a/OOjs_UI_icon_academic-progressive.svg"
#      proficiency: 2020 - Current
#      description: "General machine learning methods and applied research."

#    - name: "Representation Learning"
#      logo: "https://upload.wikimedia.org/wikipedia/commons/2/2a/OOjs_UI_icon_academic-progressive.svg"
#      proficiency: 2024 - 2025
#      description: "Learning meaningful embeddings and feature representations from data."

    Language:
    - name: "English"
      logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/OOjs_UI_icon_language-ltr-progressive.svg"
      proficiency: Experienced
      description: 

#    - name: "Taiwanese Hokkien"
#      logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/OOjs_UI_icon_language-ltr-progressive.svg"
#      proficiency: Native
#      description: "Native fluency."
