# =====================================================
# Website Configuration
# This section contains general information about your website.
# =====================================================

site:
  name: "Cookie"
  repoUrl: "https://github.com/icevalon/whoami"
  description: "Welcome to Cookie's Website"
  author: "Cookie"
